# This e2e test performs the following via a GitHub Actions push event.
# - Build the Go application
# - Generate SLSA provenance for the binary
# - Upload the provenance to a GitHub release
# - Verify the created provenance attestation.

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions: read-all

concurrency: "e2e.generic.push.main.upload-tag-name.slsa3"

env:
  GH_TOKEN: ${{ secrets.E2E_GENERIC_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator
  DEFAULT_VERSION: v32.0.0

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-push.sh

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.head_commit.message == github.workflow
    outputs:
      binary-name: ${{ steps.build.outputs.binary-name }}
      digest: ${{ steps.hash.outputs.digest }}
      upload-tag-name: ${{ steps.hash.outputs.upload-tag-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@95c9bf48d0c570bb3e28e57108f3450cd67c1a44 # tag=v2.0.0
        with:
          bazelisk-version: "1.11"
      - name: Build artifact
        id: build
        run: |
          bazelisk build //:hello
          cp bazel-bin/hello_/hello . # Copy binary from Bazel path to root
          echo "binary-name=hello" >> "${GITHUB_OUTPUT}"
      - name: Upload binary
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: ${{ steps.build.outputs.binary-name }}
          path: ${{ steps.build.outputs.binary-name }}
          if-no-files-found: error
          retention-days: 5
      - name: Generate hash
        shell: bash
        id: hash
        env:
          BINARY_NAME: ${{ steps.build.outputs.binary-name }}
        run: |
          set -euo pipefail
          source "./.github/workflows/scripts/e2e-utils.sh"
          echo "digest=$(sha256sum "${BINARY_NAME}" | base64 -w0)" >> "${GITHUB_OUTPUT}"

          filename="$(e2e_this_file)"
          filename="${filename%.*}" # Remove the file extension.
          echo "upload-tag-name=${filename}" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    if: github.event_name == 'push' && github.event.head_commit.message == github.workflow
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    with:
      base64-subjects: "${{ needs.build.outputs.digest }}"
      compile-generator: true
      upload-assets: true
      # NOTE: For non-tag triggers this will still upload to a tag.
      upload-tag-name: "${{ needs.build.outputs.upload-tag-name }}"

  verify:
    runs-on: ubuntu-latest
    needs: [build, provenance]
    if: github.event_name == 'push' && github.event.head_commit.message == github.workflow
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b
        with:
          name: ${{ needs.build.outputs.binary-name }}
      - uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b
        with:
          name: ${{ needs.provenance.outputs.attestation-name }}
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: "1.21"
      - env:
          BINARY: ${{ needs.build.outputs.binary-name }}
          PROVENANCE: ${{ needs.provenance.outputs.attestation-name }}
        run: ./.github/workflows/scripts/e2e.generic.default.verify.sh

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build, provenance, verify]
    if: github.event_name == 'push' && github.event.head_commit.message == github.workflow && needs.build.result == 'success' && needs.provenance.result == 'success' && needs.verify.result == 'success'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-report-success.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [build, provenance, verify]
    if: always() && github.event_name == 'push' && github.event.head_commit.message == github.workflow && (needs.build.result == 'failure' || needs.provenance.result == 'failure' || needs.verify.result == 'failure')
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
