on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions: read-all

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: mv e2e/maven/pom.xml ./ && cp -r e2e/maven/src ./ && rm -r e2e/maven/src

  build:
    #runs-on: ubuntu-latest
    permissions:
      id-token: write # For signing.
      contents: read # For repo checkout of private repos.
      actions: read # For getting workflow run on private repos.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_maven_slsa3.yml@main

  verify:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: slsa-framework/slsa-github-generator/.github/actions/secure-download-folder@main
        with:
          name: "${{ needs.build.outputs.provenance-download-name }}"
          sha256: "${{ needs.build.outputs.provenance-download-sha256 }}"
          path: slsa-attestations
      - uses: slsa-framework/slsa-github-generator/.github/actions/secure-download-folder@main
        with:
          name: target
          sha256: "${{ needs.build.outputs.target-download-sha256 }}"
          path: ./
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: "1.18"
      - env:
          BINARY: ./target/test-java-project-0.1.19.jar
          PROVENANCE: "slsa-attestations/${{ needs.build.outputs.provenance-download-name }}/test-java-project-0.1.19.jar.build.slsa"
          BUILDER_TAG: "v2.0.0"
        run: ./.github/workflows/scripts/e2e.maven.default.verify.sh
