# This e2e test performs the following via a GitHub Actions workflow_dispatch event.
# - Trigger a GCB build via manual invocation with the cloudbuild.yaml
# - TODO: Verify the created provenance attestation.

on:
  # TODO: Add a daily schedule cron for verify.
  schedule:
    # Twice a month scheduled cron for rebuilding.
    - cron: "0 3 1,15 * *"
  workflow_dispatch:

permissions: {}

concurrency: "e2e.gcb.workflow_dispatch.main.dockerfile.slsa3"

env:
  GH_TOKEN: ${{ secrets.E2E_CONTAINER_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator

  IMAGE_REGISTRY: us-west2-docker.pkg.dev
  IMAGE_NAME: slsa-tooling/example-package-repo/e2e-gcb-workflow_dispatch-main-dockerfile-slsa3

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 3 1,15 * *'
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: ./.github/workflows/scripts/e2e-dispatch.sh

  # Trigger the GCB build
  build:
    if: github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write # For auth.
      contents: read # For reading repository contents.
      packages: write # For writing container images.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/819720953812/locations/global/workloadIdentityPools/example-package-pool/providers/example-package-provider"
          service_account: "example-package-user@slsa-tooling.iam.gserviceaccount.com"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b" # v1.1.1
      - name: Trigger build via manual invocation
        id: build
        run: |
          gcloud builds submit --region=us-west2 --project slsa-tooling --suppress-logs --tag "${IMAGE_REGISTRY}/${IMAGE_PROJECT}/${IMAGE_NAME}" --gcs-log-dir:gs://slsa-tooling_coudbuild/

          # Retrieve the latest build ID
          # TODO: How do we avoid races? Can we directly get the output of builds submit?
          build_id=$(gcloud builds --verbosity debug list --region=us-west2 --project slsa-tooling --limit=1 --format="value(id)")
          echo "Created build with build id ${build_id}..."

          image_digest=$(gcloud builds --verbosity debug describe "${build_id}" --project=slsa-tooling --region=us-west2 --format="value(results.images[0].digest)")
          echo "Retrieved image digest ${image_digest}..."

          escaped_image_name=$(echo "${image_name}" | sed "s/\//%2F/g")
          gcloud artifacts docker images describe "${IMAGE_REGISTRY}/${escaped_image_name}@${image_digest}" --verbosity debug --show-provenance
